Added reactstrap dependency & simple form page for recipes   Closes #6
mycodecareer/30daygroupproject pull request #44
Opened 2023-03-24 16:34 UTC by koliosor

## Overview

## Checklist

- [ ] New and updated code has appropriate documentation
- [ ] New and updated code has new and/or updated testing
- [ ] Required CI checks are passing
- [ ] Visual proof for any user facing features like CLI or documentation updates
- [ ] Linked issues closed with keywords

2023-03-25 20:58 UTC, MSevey requested changes
Great start! Nice use of the reusable react component to build the Form 👍🏼

Mainly my comments are focused on why we aren't using the already installed `react-bootstrap` library and adding a new library. The library should be very similar so just updating to use `react-bootstrap` should be pretty painless.

2023-03-25 20:58 UTC, MSevey commented on frontend/package.json
> +    "reactstrap": "^9.1.6",
Why did we add `reactstrap`? We already have `react-bootstrap` in this project.

2023-03-25 20:58 UTC, MSevey commented on frontend/src/App.js
> +import "./App.css";
```suggestion
```
This is a duplicate import

2023-03-25 20:58 UTC, MSevey commented on frontend/src/App.js
>        <header className="App-header">
```suggestion
```

You should be able to remove these as well now, which would allow you to not import the `App.css` either as it would no longer be used.

2023-03-25 20:58 UTC, MSevey commented on frontend/src/Form.js
> +} from "reactstrap";
can we use `react-bootstrap` instead as that was already insalled?

2023-03-25 20:58 UTC, MSevey commented on frontend/src/Form.js
> +import "bootstrap/dist/css/bootstrap.min.css";
same, this shouldn't be needed if we are using `react-bootstrap`

2023-03-25 20:58 UTC, MSevey commented on frontend/src/index.js
> +import App from "./App";
```suggestion
```

You don't need this

2023-03-25 20:58 UTC, MSevey commented on frontend/src/index.js
> -import "bootstrap/dist/css/bootstrap.min.css";
If we revert back to `react-bootstrap` we will need this

2023-03-25 21:00 UTC, MSevey commented on frontend/src/index.js
> +    element: <MyForm />,
Instead of replacing this, the idea is to add a new route like:
```javascript
{
  path: "/new?;
  element: <MyForm />,
}
```

2023-03-29 17:16 UTC, koliosor reviewed
Fixed the issues you mentioned. i removed reactstrap and imported normal bootstrap again.

2023-03-30 14:58 UTC, merged